version: '2'
services:
  redis:
    image: redis:6.2.6
    container_name: redis
    restart: always
    hostname: deceit-redis
    networks:
      - deceit
    ports:
      - "6400:6379"
  de-ce-it-server:
    image: de-ce-it-server
    container_name: de-ce-it-server
    restart: always
    depends_on:
      - redis
    networks:
      - deceit
    ports:
      - "8080:8080"
  de-ce-it-webapp:
      image: de-ce-it-webapp
      container_name: de-ce-it-webapp
      restart: always
      networks:
        - deceit
      ports:
        - "80:80"

networks:
  deceit:
    name: deceit
    driver: bridge

